CC = x86_64-w64-mingw32-gcc
CFLAGS = -Wall -O2
TARGETS = PC8TOPPC.exe PC8TOP86.exe WAV2PC8.exe

all: $(TARGETS)

PC8TOPPC.exe: pc8toppc.c
	$(CC) $(CFLAGS) pc8toppc.c -o PC8TOPPC.exe

PC8TOP86.exe: pc8top86.c
	$(CC) $(CFLAGS) pc8top86.c -o PC8TOP86.exe
	
WAV2PC8.exe: wav2pc8.c
	$(CC) $(CFLAGS) wav2pc8.c -o WAV2PC8.exe

clean:
	rm -f $(TARGETS)
